### ISSUE TITLE
afcrc-helper: Cannot deny a redirect request

### ISSUE THREAD

**Issue by garsh1** [Eejit43/wikipedia-scripts#123]
Hello, 

It appears that the script can no longer be used to deny redirect requests. If the script is run with any redirect marked as "deny", the script does not work correctly. It appears to open part of the running interface, as shown below. No actual edits are made, however.  I have not tried this with a category.

![image](https://github.com/user-attachments/assets/fe2554c5-460a-4f02-8e0d-752f0cc838e8)

Note to developers/maintainers of this script: Thank you! This script is immensely helpful. Apologies if I did not format this issue correctly. I don't use GitHub very often.

**Comment by Eejit43** [comment]
@garsh1 This issue has now been resolved, thank you so much for reporting! I'm glad you've found the script helpful :)
