### ISSUE TITLE
`redirect-helper`: Make inputting certain redirects supported

### ISSUE THREAD

**Issue by aaronliu0130** [Eejit43/wikipedia-scripts#76]
Redirects such as {{r from alternative punctuation}} are meant so maybe one day a more specific template can be added. It'd be of great benefit if we could add these intentional redirects too.

**Comment by Eejit43** [comment]
Interesting... I'd say why not go ahead and make those templates? Seems like {{[R from alternative hyphenation](https://en.wikipedia.org/w/index.php?title=Template:R_from_alternative_hyphenation&redirect=no)}}, {{[R from alternative punctuation](https://en.wikipedia.org/w/index.php?title=Template:R_from_alternative_punctuation&redirect=no)}}, and {{[R from alternative spacing](https://en.wikipedia.org/w/index.php?title=Template:R_from_alternative_spacing&redirect=no)}} are the ones that should be done, along with other redirects that should be retargeted to those new templates. I'd be happy to do that. If you think that isn't a good idea, this would be a pretty simple addition however.

**Comment by Eejit43** [comment]
The templates have been made and the script has been updated! I'm still in the process of updating all avoided double redirects, and my edit request to {{[R from alternative punctuation](https://en.wikipedia.org/w/index.php?title=Template:R_from_alternative_punctuation&redirect=no)}} hasn't been approved yet, but the script will function nonetheless.

**Comment by aaronliu0130** [comment]
Great job! I feel like you're really close to an admin already :p
